version: '3.9'

services:
  app:
    container_name: app
    build:
      context: ./server/app
      dockerfile: Dockerfile
    volumes:
      - ./server/app:/var/www
    depends_on:
      - web
      - db
    env_file:
      - .env

  web:
    build:
      context: ./server/nginx
      dockerfile: Dockerfile
    container_name: web
    ports:
      - ${WEB_SERVER_PUBLISHED_PORT:-80}:${WEB_SERVER_TARGET_PORT:-80}
    volumes:
      - ./server/app:/var/www

  db:
    image: postgres:15
    container_name: db
    ports:
      - ${DB_SERVER_PUBLISHED_PORT:-5432}:${DB_SERVER_TARGET_PORT:-5432}
    environment:
      - POSTGRES_DB=${DB_DATABASE:-postgres}
      - POSTGRES_USER=${DB_USER:-root}
      - POSTGRES_PASSWORD=${DB_PASSWORD?}