version: '3'
services:
  app:
    container_name: app
    image: php:8.1-fpm-alpine
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - app


  db:
    image: mysql:8
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=root