version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/var/www/laravel-docker
    depends_on:
      - db

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: web
    ports:
      - "80:80"
    volumes:
      - ./html/:/var/www/html/
      - ./logs/nginx:/var/log/nginx/
    depends_on:
      - app


  db:
    image: mysql:8
    container_name: db
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ./db:/var/lib/mysql

    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}