version: '3.9'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: app/Dockerfile
    volumes:
      - ./app:/var/www
    depends_on:
      - web

  web:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    container_name: web
    ports:
      - ${WEB_SERVER_PORT:-8080}:${WEB_SERVER_PORT:-8080}
    volumes:
      - ./app:/var/www

  db:
    image: postgres:15
    container_name: db
    ports:
      - ${DB_PORT:-5432}:${DB_PORT:-5432}
    environment:
      - POSTGRES_DB=${DB_DATABASE}
      - POSTGRES_PASSWORD=${DB_PASSWORD?}