#version: "3"
#services:
 # nginx:
 #   image: nginx:alpine
 #   ports:
 #     - "8080:80"

version: '3'
services:
  app:
    image: php:8.1-fpm-alpine

  web:
    image: nginx:alpine
    ports:
      - "80:80"

  mysql:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root